### ISSUE TITLE
FRP: allow protocol version to be a useable variable in strategies

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/ydaemon#220] opened 2023-03-08 20:21 UTC
When writing a description in meta such as https://github.com/yearn/ydaemon/blob/develop/data/meta/strategies/10/AaveOptimizer.json make is so we can add the protocol version and it would output the number.

would look like this:
Supplies {{token}} to [AAVE](https://app.aave.com/home) v{{protocolVersion:Aave}} to generate interest...

This would let me input the protocol version fields without having to hardcode them.

**Comment by udhaykumarbala** [comment] 2023-07-26 03:37
Hi @0xBasically, can i work on this

**Comment by udhaykumarbala** [comment] 2023-07-29 15:33
Hi @0xBasically, can you please explain the issue little

**Comment by 0xBasically** [comment] 2023-08-03 21:00
Hey there is logic in the meta section scheme maybe that lets one do this ""Supplies {{token}} to [AAVE](https://app.aave.com/home) v3 to generate interest," https://github.com/yearn/ydaemon/blob/develop/data/meta/strategies/10/AaveOptimizer.json 
and it will show the token name of that strategy address, https://yearn.finance/vaults/1/0xa258C4606Ca8206D8aA700cE2143D7db854D168c?tab=strategies see the aave strategy 
![image](https://github.com/yearn/ydaemon/assets/131375535/f92df9a9-6408-479c-aeef-17fe5da05cf9)
The issue is asking for that same logic but for protocol version names, and to pull it from https://github.com/yearn/ydaemon/blob/develop/data/meta/protocols/1/1inch.json#L4 looking up the correct protocol, their version and outputting the version number so defaulting to the latest (highest) version. Basically a way to pass info that can be outputted / substituted into the text, can be protocol and protocol version. Maybe it is just easier to hard code things this would see if this method is possible/makes sense. A way to simplify writing descriptions, by pulling in the data we already have in ydeamon/meta.

**Comment by 0xBasically** [comment] 2023-08-17 14:23
Closing this not needed atm, but if anyone wants to pick it up and optimize this section feel free.

**Closed by 0xBasically** 2023-08-17 14:23 UTC
Labels: enhancement, help wanted, good first issue, meta
